apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon
spec:
  selector:
    matchLabels:
      app: amazon
  replicas: 2
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: amazon
        image: thuyein97/amazon-prime:28
        ports:
        - containerPort: 3000
